import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  brand900: '#1e3a8a',
  brand800: '#1e40af',
  brand700: '#1d4ed8',
  brand500: '#3b82f6',
  brand300: '#93c5fd',
  brand200: '#bfdbfe',
  brand100: '#dbeafe',
  brand50: '#eff6ff',
  slate900: '#0f172a',
  slate800: '#1e293b',
  slate700: '#334155',
  slate600: '#475569',
  slate500: '#64748b',
  slate400: '#94a3b8',
  slate300: '#cbd5e1',
  slate200: '#e2e8f0',
  slate100: '#f1f5f9',
  slate50: '#f8fafc',
  red800: '#991b1b',
  red700: '#b91c1c',
  red500: '#ef4444',
  red100: '#fee2e2',
  red50: '#fef2f2',
  white: '#ffffff',
} as const;

const FONT = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_OBLIQUE = 'Helvetica-Oblique';

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: FONT,
    fontSize: 9.5,
    color: colors.slate800,
    paddingTop: 62,
    paddingBottom: 70,
    paddingHorizontal: 36,
    lineHeight: 1.45,
  },

  // ─── Header ────────────────────────────────────────────
  header: {
    position: 'absolute',
    top: 18,
    left: 36,
    right: 36,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate200,
    borderBottomStyle: 'solid',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLogo: {
    width: 22,
    height: 28,
    marginRight: 8,
  },
  headerTextBlock: {
    flexDirection: 'column',
  },
  headerBrand: {
    fontFamily: FONT_BOLD,
    fontSize: 13,
    color: colors.brand900,
    letterSpacing: 2,
    lineHeight: 1.1,
  },
  headerTagline: {
    fontFamily: FONT,
    fontSize: 7,
    color: colors.slate500,
    lineHeight: 1.2,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  headerDate: {
    fontFamily: FONT_BOLD,
    fontSize: 9,
    color: colors.brand900,
    lineHeight: 1.2,
  },
  headerRef: {
    fontFamily: FONT,
    fontSize: 8,
    color: colors.slate500,
    lineHeight: 1.2,
    marginTop: 3,
  },

  // ─── Footer ────────────────────────────────────────────
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    right: 36,
    borderTopWidth: 1,
    borderTopColor: colors.slate200,
    borderTopStyle: 'solid',
    paddingTop: 8,
    flexDirection: 'column',
  },
  footerLine: {
    fontFamily: FONT,
    fontSize: 7,
    color: colors.slate500,
    lineHeight: 1.4,
    textAlign: 'center',
  },
  pageNumber: {
    position: 'absolute',
    right: 0,
    top: -4,
    fontFamily: FONT,
    fontSize: 7,
    color: colors.slate500,
  },

  // ─── Cover ─────────────────────────────────────────────
  coverBlock: {
    flexDirection: 'column',
    marginBottom: 18,
  },
  coverTitle: {
    fontFamily: FONT_BOLD,
    fontSize: 22,
    color: colors.brand900,
    letterSpacing: 2,
    textTransform: 'uppercase',
    lineHeight: 1.15,
    marginBottom: 6,
  },
  coverSubtitle: {
    fontFamily: FONT,
    fontSize: 10,
    color: colors.brand700,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    lineHeight: 1.2,
  },
  coverRule: {
    height: 3,
    backgroundColor: colors.brand900,
    marginTop: 10,
  },

  // ─── Section titles ────────────────────────────────────
  sectionTitle: {
    fontFamily: FONT_BOLD,
    fontSize: 12,
    color: colors.brand900,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    borderBottomWidth: 2,
    borderBottomColor: colors.brand200,
    borderBottomStyle: 'solid',
    paddingBottom: 4,
    marginTop: 14,
    marginBottom: 12,
    lineHeight: 1.2,
  },
  subtitle: {
    fontFamily: FONT_BOLD,
    fontSize: 8.5,
    color: colors.brand700,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    lineHeight: 1.3,
    marginBottom: 6,
  },

  // ─── Info row (Demandeur / Technicien) ─────────────────
  infoRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  infoCol: {
    flexDirection: 'column',
    flex: 1,
  },
  infoColSpacer: { width: 12 },
  infoBlock: {
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: colors.brand200,
    borderStyle: 'solid',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  infoBlockPrimary: { backgroundColor: colors.brand50 },
  infoName: {
    fontFamily: FONT_BOLD,
    fontSize: 12,
    color: colors.brand900,
    lineHeight: 1.25,
    marginBottom: 4,
  },
  infoRole: {
    fontFamily: FONT_OBLIQUE,
    fontSize: 8.5,
    color: colors.brand700,
    lineHeight: 1.3,
    marginBottom: 8,
  },
  infoLine: {
    fontFamily: FONT,
    fontSize: 8.5,
    color: colors.slate700,
    lineHeight: 1.4,
    marginBottom: 2,
  },
  infoSeparator: {
    height: 1,
    backgroundColor: colors.brand200,
    marginVertical: 6,
  },

  // ─── Rappel & contexte ─────────────────────────────────
  rappelBox: {
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: colors.brand100,
    borderStyle: 'solid',
    backgroundColor: colors.brand50,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  rappelText: {
    fontFamily: FONT,
    fontSize: 9,
    color: colors.slate700,
    lineHeight: 1.5,
    marginBottom: 6,
  },
  rappelStrong: {
    fontFamily: FONT_BOLD,
    color: colors.brand900,
  },
  warningBox: {
    backgroundColor: colors.red50,
    borderWidth: 1,
    borderColor: colors.red100,
    borderStyle: 'solid',
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  warningText: {
    fontFamily: FONT,
    fontSize: 8.5,
    color: colors.red800,
    lineHeight: 1.45,
  },

  // ─── Bullet list ───────────────────────────────────────
  list: {
    flexDirection: 'column',
    marginLeft: 8,
    marginTop: 2,
    marginBottom: 4,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  bullet: {
    fontFamily: FONT,
    width: 10,
    fontSize: 9,
    color: colors.brand700,
    lineHeight: 1.4,
  },
  listText: {
    flex: 1,
    fontFamily: FONT,
    fontSize: 9,
    color: colors.slate700,
    lineHeight: 1.4,
  },

  // ─── Tables ────────────────────────────────────────────
  table: {
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: colors.brand200,
    borderStyle: 'solid',
    marginBottom: 12,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderBottomWidth: 1,
    borderBottomColor: colors.brand200,
    borderBottomStyle: 'solid',
  },
  tableRowLast: { borderBottomWidth: 0 },
  tableHeaderRow: { backgroundColor: colors.brand900 },
  tableCell: {
    flexDirection: 'column',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRightWidth: 1,
    borderRightColor: colors.brand200,
    borderRightStyle: 'solid',
  },
  tableCellLast: { borderRightWidth: 0 },
  tableCellLabel: {
    backgroundColor: colors.brand50,
  },
  th: {
    fontFamily: FONT_BOLD,
    fontSize: 8.5,
    color: colors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    lineHeight: 1.3,
  },
  tdLabel: {
    fontFamily: FONT_BOLD,
    fontSize: 9,
    color: colors.brand900,
    lineHeight: 1.4,
  },
  td: {
    fontFamily: FONT,
    fontSize: 9,
    color: colors.slate700,
    lineHeight: 1.45,
  },
  tdMuted: {
    fontFamily: FONT_OBLIQUE,
    color: colors.slate500,
  },

  // ─── Symptoms two-column ───────────────────────────────
  symptomsRow: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  symptomsCol: {
    flexDirection: 'column',
    flex: 1,
  },
  symptomsColSpacer: { width: 12 },
  symptomsHeader: {
    backgroundColor: colors.brand200,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.brand300,
    borderStyle: 'solid',
  },
  symptomsHeaderText: {
    fontFamily: FONT_BOLD,
    fontSize: 8.5,
    color: colors.brand900,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
    lineHeight: 1.3,
  },
  symptomsBody: {
    flexDirection: 'column',
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: colors.brand300,
    borderStyle: 'solid',
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: colors.white,
    minHeight: 70,
  },

  // ─── Conclusion ────────────────────────────────────────
  conclusionWrap: {
    flexDirection: 'column',
    marginTop: 12,
  },
  conclusionHeader: {
    backgroundColor: colors.brand900,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  conclusionHeaderText: {
    fontFamily: FONT_BOLD,
    fontSize: 9,
    color: colors.white,
    textTransform: 'uppercase',
    letterSpacing: 1,
    lineHeight: 1.2,
  },
  conclusionBody: {
    flexDirection: 'column',
    borderWidth: 2,
    borderColor: colors.brand900,
    borderTopWidth: 0,
    borderStyle: 'solid',
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.white,
  },
  conclusionParagraph: {
    fontFamily: FONT,
    fontSize: 9,
    color: colors.slate800,
    lineHeight: 1.6,
    marginBottom: 7,
    textAlign: 'justify',
  },
  conclusionMarker: {
    fontFamily: FONT_BOLD,
    fontSize: 9,
    color: colors.brand700,
    textAlign: 'center',
    letterSpacing: 0,
    marginVertical: 8,
  },

  // ─── Risks ─────────────────────────────────────────────
  risksBox: {
    flexDirection: 'column',
    borderWidth: 2,
    borderColor: colors.red100,
    borderStyle: 'solid',
    marginBottom: 14,
    marginTop: 6,
  },
  risksHeader: {
    backgroundColor: colors.red50,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.red100,
    borderBottomStyle: 'solid',
  },
  risksHeaderText: {
    fontFamily: FONT_BOLD,
    fontSize: 9,
    color: colors.red800,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    lineHeight: 1.2,
  },
  risksBody: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  riskItem: {
    width: '50%',
    paddingVertical: 4,
    paddingHorizontal: 4,
    fontFamily: FONT_BOLD,
    fontSize: 8.5,
    color: colors.red800,
    lineHeight: 1.4,
  },

  // ─── Légende outils de mesure ──────────────────────────
  legendBox: {
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: colors.brand200,
    borderStyle: 'solid',
    backgroundColor: colors.brand50,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  legendItem: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  legendItemLast: {
    marginBottom: 0,
  },
  legendBullet: {
    width: 10,
    fontFamily: FONT,
    fontSize: 9,
    color: colors.brand700,
    lineHeight: 1.45,
  },
  legendText: {
    flex: 1,
    fontFamily: FONT,
    fontSize: 8.5,
    color: colors.brand900,
    lineHeight: 1.45,
  },

  // ─── Synthese mesures ──────────────────────────────────
  syntheseBox: {
    flexDirection: 'column',
    borderWidth: 1,
    borderColor: colors.brand200,
    borderStyle: 'solid',
    backgroundColor: colors.brand50,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  syntheseLabel: {
    fontFamily: FONT_BOLD,
    fontSize: 8,
    color: colors.brand500,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
    lineHeight: 1.3,
  },
  syntheseText: {
    fontFamily: FONT_OBLIQUE,
    fontSize: 9,
    color: colors.brand900,
    lineHeight: 1.5,
  },

  // ─── Signatures ────────────────────────────────────────
  signaturesRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: 1,
    borderColor: colors.brand300,
    borderStyle: 'solid',
    marginTop: 10,
  },
  signatureCell: {
    flexDirection: 'column',
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  signatureCellDivider: {
    borderRightWidth: 1,
    borderRightColor: colors.brand300,
    borderRightStyle: 'solid',
  },
  signatureLabel: {
    fontFamily: FONT_BOLD,
    fontSize: 8,
    color: colors.brand900,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    lineHeight: 1.3,
    marginBottom: 4,
  },
  signatureHint: {
    fontFamily: FONT_OBLIQUE,
    fontSize: 7.5,
    color: colors.slate500,
    lineHeight: 1.3,
    marginBottom: 6,
  },
  signatureBox: {
    flexDirection: 'column',
    height: 90,
    borderWidth: 1,
    borderColor: colors.brand100,
    borderStyle: 'solid',
    backgroundColor: colors.brand50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  signatureImage: {
    height: 84,
    width: '95%',
    objectFit: 'contain',
  },
  signaturePlaceholder: {
    fontFamily: FONT_OBLIQUE,
    fontSize: 8,
    color: colors.brand200,
    lineHeight: 1.3,
  },
  signatureFooter: {
    fontFamily: FONT,
    fontSize: 7.5,
    color: colors.brand700,
    lineHeight: 1.3,
  },

  // ─── Photo annex ───────────────────────────────────────
  annexHeader: {
    flexDirection: 'column',
    borderBottomWidth: 3,
    borderBottomColor: colors.brand900,
    borderBottomStyle: 'solid',
    paddingBottom: 6,
    marginBottom: 16,
  },
  annexTitle: {
    fontFamily: FONT_BOLD,
    fontSize: 18,
    color: colors.brand900,
    textTransform: 'uppercase',
    letterSpacing: 2,
    lineHeight: 1.15,
    marginBottom: 4,
  },
  annexSubtitle: {
    fontFamily: FONT_OBLIQUE,
    fontSize: 9,
    color: colors.slate500,
    lineHeight: 1.3,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  photoCard: {
    flexDirection: 'column',
    width: '48.5%',
    borderWidth: 1,
    borderColor: colors.brand200,
    borderStyle: 'solid',
    paddingVertical: 6,
    paddingHorizontal: 6,
    backgroundColor: colors.white,
    marginBottom: 12,
  },
  photoCardRight: { marginLeft: '3%' },
  photoImageBox: {
    flexDirection: 'column',
    height: 200,
    backgroundColor: colors.slate100,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  photoImage: {
    height: 196,
    width: '98%',
    objectFit: 'contain',
  },
  photoCaption: {
    fontFamily: FONT_BOLD,
    fontSize: 8,
    color: colors.brand800,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
    backgroundColor: colors.brand50,
    paddingVertical: 4,
    lineHeight: 1.3,
  },

  // ─── Helpers ───────────────────────────────────────────
  bold: { fontFamily: FONT_BOLD },
  italic: { fontFamily: FONT_OBLIQUE },
  muted: { color: colors.slate500, fontFamily: FONT_OBLIQUE },
});
